---
host: "https://<your-domain-here>"
yield_dir: "yield"
#secret: "<optional-access-secret>"
auth:
  email: "<your-email-here>"
  password: "<your-password-here>"
podcasts:
#  papaya:
#    feed_name: "papayayaya"
#    most_recent_episodes_limit: 50
#  gi-meg-alle-detaljene:
#  konspirasjonspodden:
...
